management:
  endpoints:
    web:
      exposure:
        include: env
      base-path: /actuator
#Configuration Properties to be read by ConfigDemoProperties
#Configuration Properties to be read by ConfigDemoProperties
config:
  demo:
    #Simple String property
    product: bullshit
    # Enum Value
    delivery: dev
    # LocalDate
    date: 2020-02-16
    #List
    products:
      - tomatos
      - cucumber
      - other
    #List of converted objects
    deadlines:
      - 2020-02-16
      - 2020-02-17
    #Simple Map<String,String>
    simplepairs:
      key1: value1
      key2: value2

    nested:
      name: John
      birthDate: 1961-12-15


